### ISSUE TITLE
Customization of title in DNA methylseq analysis

### ISSUE THREAD

**Issue by Rasika12345** [KongLabRUSP/Project.RNA.and.DNA.seq.data.analysis.Shiny.app#2]
In DNA methyseq analysis, exploratory analysis, Heatmap of methyl% on gene level, the title should be changed. Always shows top 20 genes.

**Comment by sargdavid** [comment]
Done. Use a clean copy in the new repository:
[https://github.com/KongLabRUSP/shiny.ngs](https://github.com/KongLabRUSP/shiny.ngs)
